FROM zenika/alpine-kotlin:1.2-jdk8

WORKDIR /home/workdir
RUN apk --update add git gradle maven
#RUN git clone https://github.com/Jumpaku/UnitsOfMeasure.git /home/
#RUN ./gradlew build

CMD [ "bash" ]